from pygame import Color

BACKGROUND_COLOR = Color('#2b2d42')
BLOOD_COLOR = Color('#ef233c')
DARK_BLOOD_COLOR = Color('#d90429')
WHITE_COLOR = Color('#ffffff')
GREY_ACCENT_COLOR = Color('#8d99ae')
GREY_HOVER_ACCENT_COLOR = Color('#959FB1')

MAINMENU_BUTTON_BACKGROUND_COLOR = Color('#8d99ae')
MAINMENU_BUTTON_BACKGROUND_HOVER_COLOR = Color('#9CA8BD')
MAINMENU_BUTTON_TEXT_COLOR = Color('#ef233c')


# '#2b2d42'
# '#8d99ae'

#(43, 45, 66)